version: "3.8"

services:
  db:
    build:
      context: .
      dockerfile: ./Dockerfile-db
    restart: on-failure
    environment:
      - POSTGRES_DB=human_api_db
      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - db-data:/var/lib/postgresql/data

  flask_app:
    depends_on:
      - db
    links:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    environment:
      - FLASK_APP=./src/main.py
      - FLASK_ENV=development
    volumes:
      - .:/humanAPI
    ports:
      - "5000:5000"
